USE [master]
GO

/****** Object:  Database [AzureIdsDb]    Script Date: 2015-05-03 19:34:50 ******/
DROP DATABASE [AzureIdsDb]
GO

/****** Object:  Database [AzureIdsDb]    Script Date: 2015-05-03 19:34:50 ******/
CREATE DATABASE [AzureIdsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AzureIdsDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\AzureIdsDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AzureIdsDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\AzureIdsDb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AzureIdsDb] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AzureIdsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AzureIdsDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AzureIdsDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AzureIdsDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AzureIdsDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AzureIdsDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [AzureIdsDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AzureIdsDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AzureIdsDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AzureIdsDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AzureIdsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AzureIdsDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AzureIdsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AzureIdsDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AzureIdsDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AzureIdsDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AzureIdsDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AzureIdsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AzureIdsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AzureIdsDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AzureIdsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AzureIdsDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AzureIdsDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AzureIdsDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AzureIdsDb] SET RECOVERY FULL 
GO

ALTER DATABASE [AzureIdsDb] SET  MULTI_USER 
GO

ALTER DATABASE [AzureIdsDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AzureIdsDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AzureIdsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AzureIdsDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AzureIdsDb] SET  READ_WRITE 
GO


